neural_network:
  architechture: resnet101 # resnet50 resnet101
  data_type: img # img or audio or mel or multi_modal
  use_n_seconds: 3
  batch_size: 8
  val_split_size: 0.02 # 5%
  val_check_n_epochs: 1
  epochs: 35
  log_step: 50
  seed: 42
  load_trained_model: #logs/120-mel-resnet101/model.ckpt

  optim:
    learning_rate: 1.05e-3
    momentum: 0.9
    
  scheduler:
    mode: 'max'
    factor: 0.5
    patience: 3
    cooldown: 3
    min_lr: 5.0e-7
