neural_network:
  architechture: resnet101 # resnet50 resnet101
  data_type: mel # img or audio or mel or multi_modal
  use_n_seconds: 4
  batch_size: 128
  val_split_size: 0.02 # 5%
  val_check_n_epochs: 1
  epochs: 60
  log_step: 50
  seed: 42
  load_trained_model: logs/60-mel-resnet101/model.ckpt

  optim:
    learning_rate: 1.05e-4
    momentum: 0.9
  scheduler:
    mode: 'max'
    factor: 0.5
    patience: 3
    cooldown: 3
    min_lr: 5.0e-7
